version: '3'
services:
  app_task:
    build:
      context: ./docker/php
    container_name: app_task
    tty: true
    ports:
      - '9000:9000'
    restart: always
    working_dir: /home/www
    volumes:
      - task_volume_sync:/home/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - '9000'
    networks:
      - task-network

  task_nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - task_volume_sync:/home/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: task_nginx
    networks:
      - task-network

  task_mariadb:
    image: mariadb:10.5
    container_name: task_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  task_volume_sync:
    external: true
