<?php

declare(strict_types=1);

namespace Tests\Feature\Category;

use App\Repository\UserRepository;
use Tests\TestCase;

class CategoryTest extends TestCase
{
    /**
     * @var UserRepository
     */
    protected UserRepository $userRepository;

    public function testCanCreateCategory()
    {
        $admin = $this->userRepository->findOneByName('admin');
        $this->actingAs($admin)
            ->visit('/categories')
            ->see('Create')
            ->click('Create')
            ->type('Category', 'name')
            ->press('Submit')
            ->seePageIs('/categories')
        ;
    }

    public function testCanUpdateCategory()
    {
        $admin = $this->userRepository->findOneByName('admin');
        $this->actingAs($admin)
            ->visit('/categories')
            ->see('Edit')
            ->click('Edit')
            ->type('Category updated', 'name')
            ->press('Submit')
            ->seePageIs('/categories')
        ;
    }

    public function testCanDeleteCategory()
    {
        $admin = $this->userRepository->findOneByName('admin');
        $this->actingAs($admin)
            ->visit('/categories')
            ->see('Delete')
            ->see('Category updated')
            ->press('Delete')
            ->seePageIs('/categories')
            ->dontSee('Category updated')
        ;
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userRepository = app(UserRepository::class);
    }
}
