<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\User;
use App\Repository\UserRepository;
use Tests\TestCase;

class AuthenticationTest extends TestCase
{
    /**
     * @var UserRepository
     */
    protected UserRepository $userRepository;

    /**
     * @var User
     */
    protected User $user;


    public function testAdminSeesCategoriesAndItems(): void
    {
        $admin = $this->userRepository->findOneByName('admin');

        $this->actingAs($admin)
            ->visit('/home')
            ->seeStatusCode(200)
            ->see('Categories')
            ->see('Items')
        ;
    }


    public function testUserCantSeeCategoriesAndItems()
    {
        $this->actingAs($this->user)
            ->visit('/home')
            ->seeStatusCode(200)
            ->dontSee('Categories')
            ->dontSee('Items');
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userRepository = app(UserRepository::class);
        $this->user = User::factory()->create();
    }

    protected function tearDown(): void
    {
        $this->user->delete();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
